### ISSUE TITLE
git repos

### ISSUE THREAD

**Issue by edsu** [umd-mith/automation#3]
I don't know anything about ansible so I guess I should be quiet, especially since I'm still hazy on playbooks, roles and plays. But the little convo I've had with other people who use it, it seems like people tend to put roles and playbooks into their own git repos? Is there any value in doing that instead of having everything lumped together?

**Comment by trevormunoz** [comment]
Interesting. Do you have any links to repos laid out that way?

My original thinking was driven by convenience, e.g., Clone this repo, get all of our playbooks.

**Comment by edsu** [comment]
I definitely see the value in keeping it simple to start out with. From the convo I had in #code4lib slack it seems that it's considered useful to publish roles that don't already exist using [ansible-galaxy](https://galaxy.ansible.com/intro)? Did we have to create our own roles, or are we just using already existing ones?

**Comment by edsu** [comment]
Maybe if we develop any reusable roles we can spin them out of `automation`. Gonna close this till I understand enough of the terminology to make more sense.
